name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Password Generator ${{ github.ref_name }}
        body: |
          ## Password Generator Release ${{ github.ref_name }}
          
          ### Features
          - Secure password generation (4-50 characters)
          - Encrypted password library with XOR encryption
          - Clean pixel art UI with embedded assets
          - Portable single executable
          
          ### Usage
          - Download `PasswordGenerator.exe` from the assets below
          - Run directly - no installation required
          - All data stored locally in encrypted format
          
          ### System Requirements
          - Windows 10/11 (x64)
          
          **Note:** Upload the executable manually to this release.
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}